version: '3.3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./php/nginx/conf.d/demo.wordpress.local.conf:/etc/nginx/conf.d/demo.wordpress.local.conf
      - ./rbspy/nginx/conf.d/demo.publify.local.conf:/etc/nginx/conf.d/demo.publify.local.conf
      - ./java/nginx/conf.d/demo.hlebushek.local.conf:/etc/nginx/conf.d/demo.hlebushek.local.conf
      - ./java/nginx/conf.d/demo.flamescope.local.conf:/etc/nginx/conf.d/demo.flamescope.local.conf
    depends_on:
      - wordpress
      - rbspy
      - java
      - flamescope
    links:
      - rbspy
      - wordpress
      - java
      - flamescope

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=root

  wordpress:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    environment:
      - VIRTUAL_HOST=demo.wordpress.local
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./php/fpm/conf.d/xhprof_sampling.php:/usr/local/etc/php/conf.d/xhprof_sampling.php
      - ./php/fpm/conf.d/xhprof_sampling.ini:/usr/local/etc/php/conf.d/xhprof_sampling.ini
      - /tmp/:/tmp/

  juno_kv_server:
    image: bloodjazman/juno_kv_server
    entrypoint: /juno-test/bin/kv_server
    ports:
      - 6060:6060
      - 8379:8379

  go-torch:
    image: uber/go-torch
    depends_on:
      - juno_kv_server
    links:
      - juno_kv_server
    volumes:
      - /tmp/:/tmp/
    entrypoint: '/go/bin/go-torch -u http://juno_kv_server:6060 -f /tmp/go-torch-flamegraph.svg'

  rbspy:
    build:
      context: ./
      dockerfile: ./rbspy/Dockerfile
    volumes:
      - /tmp/:/tmp/
    cap_add:
      - SYS_PTRACE

  flamescope:
    build:
      context: /opt/flamescope
      dockerfile: /opt/flamescope/Dockerfile
    volumes:
      - /tmp/:/stacks/

  java:
    build:
      context: ./
      dockerfile: ./java/Dockerfile
    command: sh -c "cd /opt/hlebushek && MAVEN_OPTS='-XX:+PreserveFramePointer -Xmx512m -Xms10m' mvn jetty:run"
    volumes:
      - /tmp/:/tmp/
    privileged: true